import { Comando } from "../types"


export const comandosData: Comando[] = [
  {
    id: 1,
    comandoId: "2726289",
    quiosque: "10199",
    nomeQuiosque: "Guararapes",
    tipo: "reiniciarAplicativo",
    status: "pendente",
    criadoEm: "2024-11-14T08:19:00",
    usuario: "Alexandre Morozov",
    descricao: "Reiniciar aplicativo do quiosque para aplicar atualizações",
    duracao: null,
    resultado: null,
  },
  {
    id: 2,
    comandoId: "2726290",
    quiosque: "10200",
    nomeQuiosque: "Loja Recife",
    tipo: "reiniciarAplicativo",
    status: "pendente",
    criadoEm: "2024-11-14T08:19:00",
    usuario: "Alexandre Morozov",
    descricao: "Reiniciar aplicativo do quiosque para aplicar atualizações",
    duracao: null,
    resultado: null,
  },
  {
    id: 3,
    comandoId: "2726291",
    quiosque: "10201",
    nomeQuiosque: "Tacaruna",
    tipo: "reiniciarAplicativo",
    status: "pendente",
    criadoEm: "2024-11-14T08:19:00",
    usuario: "Alexandre Morozov",
    descricao: "Reiniciar aplicativo do quiosque para aplicar atualizações",
    duracao: null,
    resultado: null,
  },
  {
    id: 4,
    comandoId: "2726292",
    quiosque: "10202",
    nomeQuiosque: "RioMar",
    tipo: "reiniciarAplicativo",
    status: "pendente",
    criadoEm: "2024-11-14T08:19:00",
    usuario: "Alexandre Morozov",
    descricao: "Reiniciar aplicativo do quiosque para aplicar atualizações",
    duracao: null,
    resultado: null,
  },
  {
    id: 5,
    comandoId: "2726293",
    quiosque: "10200",
    nomeQuiosque: "Loja Recife",
    tipo: "carregarAplicação",
    status: "feito",
    criadoEm: "2024-11-11T05:01:00",
    usuario: null,
    descricao: "Carregar nova versão da aplicação",
    duracao: "2m 34s",
    resultado: "Sucesso - Aplicação carregada com êxito",
  },
  {
    id: 6,
    comandoId: "2726294",
    quiosque: "10200",
    nomeQuiosque: "Loja Recife",
    tipo: "reinício",
    status: "feito",
    criadoEm: "2024-11-11T05:00:00",
    usuario: null,
    descricao: "Reinicialização completa do sistema",
    duracao: "1m 45s",
    resultado: "Sucesso - Sistema reiniciado",
  },
  {
    id: 7,
    comandoId: "2726295",
    quiosque: "10199",
    nomeQuiosque: "Guararapes",
    tipo: "carregarAplicação",
    status: "executando",
    criadoEm: "2024-11-14T10:30:00",
    usuario: "Alexandre Morozov",
    descricao: "Carregar nova versão da aplicação",
    duracao: null,
    resultado: null,
  },
  {
    id: 8,
    comandoId: "2726296",
    quiosque: "10201",
    nomeQuiosque: "Tacaruna",
    tipo: "reinício",
    status: "erro",
    criadoEm: "2024-11-13T14:22:00",
    usuario: "Alexandre Morozov",
    descricao: "Reinicialização completa do sistema",
    duracao: "30s",
    resultado: "Erro - Falha na conexão com o quiosque",
  },
  {
    id: 9,
    comandoId: "2726297",
    quiosque: "10202",
    nomeQuiosque: "RioMar",
    tipo: "limparCache",
    status: "feito",
    criadoEm: "2024-11-12T16:45:00",
    usuario: "Alexandre Morozov",
    descricao: "Limpar cache e arquivos temporários",
    duracao: "45s",
    resultado: "Sucesso - Cache limpo",
  },
  {
    id: 10,
    comandoId: "2726298",
    quiosque: "10199",
    nomeQuiosque: "Guararapes",
    tipo: "atualizarSoftware",
    status: "pendente",
    criadoEm: "2024-11-14T09:15:00",
    usuario: "Alexandre Morozov",
    descricao: "Atualizar software para versão mais recente",
    duracao: null,
    resultado: null,
  },
]

export const getComandos = async (): Promise<Comando[]> => {
  // Simular delay de API
  await new Promise((resolve) => setTimeout(resolve, 500))
  return comandosData
}

export const refreshComandos = async (): Promise<Comando[]> => {
  // Simular refresh com delay
  await new Promise((resolve) => setTimeout(resolve, 1000))
  return comandosData
}
