import type { Quiosque } from "../types"

const mockQuiosques: Quiosque[] = [
  {
    id: "10202",
    nome: "10202 (RioMar)",
    status: [
      { type: "online", value: true },
      { type: "printer", value: true },
      { type: "paper", value: true },
      { type: "funnel", value: true },
      { type: "coinAcceptor", value: true },
      { type: "billValidator", value: true },
      { type: "cardReader", value: true },
      { type: "network", value: true },
    ],
    monitorMemoria: {
      value: "51 270,60 BRL",
      timeAgo: "1 ano atrás",
    },
    quantidade: "54267",
    papel: 87,
    funil: 75,
    departamento: "FotoNotaBR (Brasil)",
    predefinicaoLayout: "ATUALIZADOS",
    predefinicaoAnuncio: "falso",
    predefinicaoDocPhoto: "DOC BR",
    statusDispositivo: {
      aceitadorMoedas: {
        status: "desconectado",
        name: "Aceitador de moedas",
        properties: [
          { label: "Fabricante", value: "NRI" },
          { label: "Código do produto", value: "G13" },
          { label: "Número de série", value: "8494008" },
          { label: "Versão CCTalk", value: "DE0" },
        ],
        moeda: "BRL",
        moedaInibirStr: "0000000000001100",
        debugPollCount: 4255,
        codigosCaminho: [
          { code: "0BR005A", moeda: "5BRL" },
          { code: "1BR005B", moeda: "5BRL" },
          { code: "2BR010A", moeda: "10BRL" },
          { code: "3BR010B", moeda: "10BRL" },
          { code: "4BR010b", moeda: "10BRL" },
          { code: "5BR025A", moeda: "25BRL" },
          { code: "6BR025a", moeda: "25BRL" },
          { code: "7BR025B", moeda: "25BRL" },
          { code: "8BR050A", moeda: "50BRL" },
          { code: "9BR050a", moeda: "50BRL" },
          { code: "10BR050B", moeda: "50BRL" },
          { code: "11BR050C", moeda: "50BRL" },
          { code: "12BR100B", moeda: "100BRL" },
          { code: "13BR100C", moeda: "100BRL" },
          { code: "14TM000A", moeda: "0BRL" },
          { code: "15TM000A", moeda: "0BRL" },
        ],
      },
      validadorBillet: {
        status: "desconectado",
        name: "Validador de Billet",
        properties: [
          { label: "Fabricante", value: "ITL" },
          { label: "Código do produto", value: "NV9" },
          { label: "Número de série", value: "7749888" },
          { label: "Versão CCTalk", value: "Padrão" },
        ],
        moeda: "BRL",
        moedaInibirStr: "0110000000000000",
        debugPollCount: 4262,
        codigosCaminho: [
          { code: "0BR0002A", moeda: "200BRL" },
          { code: "1BR0005A", moeda: "500BRL" },
          { code: "2BR0010A", moeda: "1000BRL" },
          { code: "3BR0020A", moeda: "2000BRL" },
          { code: "4BR0050A", moeda: "5000BRL" },
          { code: "5BR0100A", moeda: "10000BRL" },
          { code: "6", moeda: "0BRL" },
          { code: "7", moeda: "0BRL" },
          { code: "8", moeda: "0BRL" },
          { code: "9", moeda: "0BRL" },
          { code: "10", moeda: "0BRL" },
          { code: "11", moeda: "0BRL" },
          { code: "12", moeda: "0BRL" },
          { code: "13", moeda: "0BRL" },
          { code: "14", moeda: "0BRL" },
          { code: "15", moeda: "0BRL" },
        ],
      },
      funil: {
        status: "desconectado",
        name: "Funil",
        properties: [
          { label: "Fabricante", value: "Suzo Int (Holanda)" },
          { label: "Código do produto", value: "SCH2-USE_SERNR" },
          { label: "Número de série", value: "308263" },
          { label: "Versão CCTalk", value: "padrão" },
        ],
        optoEstados: 0,
        dispanceGlobalCounter: 3849,
        valorMoeda: 100,
      },
      cortador: {
        status: "desconectado",
        name: "Cortador",
        properties: [
          { label: "Fabricante", value: "Fotonota" },
          { label: "Código do produto", value: "Cortador CCTalk" },
          { label: "Número de série", value: "0" },
          { label: "Versão CCTalk", value: "Cortador CCTalk" },
        ],
        tipoConexao: "CCtalk",
        estaCortandoAgora: false,
      },
      controladorDispositivo: {
        status: "desconectado",
        name: "Controlador de dispositivo",
        properties: [
          { label: "Fabricante", value: "Fotonota" },
          { label: "Código do produto", value: "Controlador de Fornecedores CCTalk" },
          { label: "Número de série", value: "0" },
          { label: "Versão CCTalk", value: "Controlador de Fornecedores CCTalk" },
        ],
        ultimoPing: 13,
        revisaoSoftware: "Controlador_PC_v1.15",
      },
      impressoraDnp: {
        status: "desconectado",
        name: "Impressora Dnp",
        properties: [],
        statusNativo: "STATUS_NORMALMENTE_INATIVO",
        contagemMidia: 87,
      },
      monitorMemoria: {
        status: "desconectado",
        name: "Monitor de memória",
        properties: [],
        memoriaDetalhes: [
          { name: "BATER", used: "290770", total: "1248" },
          { name: "EWF0", used: "Navegador", total: "127,80 MB 179,41 MB" },
          { name: "GPU", used: "99,10 MB", total: "181,02 MB" },
          { name: "Utilitário", used: "16,92 MB", total: "16,99 MB" },
          { name: "Aba", used: "51,58 MB", total: "60,59 MB" },
          { name: "imagens", used: "49 21,44 MB", total: "19,72 MB" },
          { name: "roteiros", used: "0 0,00 MB", total: "0,00 MB" },
          { name: "Folhas de Estilo CSS", used: "0 0,00 MB", total: "0,00 MB" },
          { name: "Folhas de Estilo xsl", used: "0 0,00 MB", total: "0,00 MB" },
          { name: "fontes", used: "0 0,00 MB", total: "0,00 MB" },
          { name: "outro", used: "0 0,00 MB", total: "0,00 MB" },
        ],
        rss: "527,42144 MB",
        heapTotal: "67,883008 MB",
        pilhaUsada: "63.348368 MB",
        externo: "6,771312 MB",
        buffersArray: "0 MB",
      },
      leitorCartaoBancario: {
        status: "desconectado",
        name: "Leitor de cartão bancário",
        properties: [],
        tipoConexao: "Brasil3",
      },
      navegador: {
        status: "desconectado",
        name: "Navegador",
        properties: [],
        versao: "9.11.17763.0",
        versaoPrincipal: 11,
        protecaoDisco: "Desabilitar",
        chave: "ChaveyEaxlBqCLQj33WLnYolxxHwSSgaJ1x",
      },
    },
    configuracoes: {
      nome: "RioMar",
      idQuiosque: "10202",
      idLegado: undefined,
      departamento: "FotoNotaBR (Brasil)",
      fonteFoto: {
        instagram: true,
        doTelefone: true,
        facebook: true,
        fotoIdentificacao: true,
      },
      predefinicaoLayout: "ATUALIZADOS",
      predefinicaoAnuncio: "falso",
      predefinicaoDocPhoto: "DOC BR",
      pagamento: {
        preco: "R$ 10,00",
        precoFotoIdentificacao: "R$ 15,00",
        usarPrecoFlexivel: true,
        oFlexPriceE: false,
        precosEspeciais: [],
        usarCodigoPromocionalTroco: false,
        codigoPromocionalAlteracao: false,
        tipoPromocaoErroImpressao: "quantidade-total-1",
        valorMinimoImpressao: "R$ 5,00",
        usarPagamentosCodigoQr: true,
        pagamentosCodigoQr: {
          ksherPromptPay: true,
          ksherAlipay: false,
          ksherTruemoney: true,
          rmTng: false,
          rmGrabPay: false,
          maybankQrPay: false,
          impulsionar: true,
          mostroReceita: false,
          bcelLaos: true,
        },
        usarNotasAceitas: true,
        aceitandoNotas: true,
        usarMoedasAceitam: true,
        aceitandoMoedas: true,
      },
      localidade: {
        usarLocalidades: true,
        localidadePadrao: "portugues",
        locais: ["Inglês", "Português", "Brasileiro"],
      },
      adicional: {
        atrasoReinicializacao: "300",
        redefinirExibicaoAtraso: "60",
        taxaPrincipalAtrasoReinicializacao: "120",
        imprimirRendaVitalicia: "sobre",
        reiniciarQuiosqueAposErros: "sobre",
        usarFotosPbAtencao: true,
        fotosPbAtencoes: true,
        usarLimiteFolhasImpressas: true,
        limiteFolhasImpressao: "1000",
        limiteMeoriaRenderizacao: "512",
        usarMargem: true,
        margem: {
          left: 44,
          right: 44,
          top: 48,
          bottom: 48,
        },
      },
      hardware: {
        usarRegiao: true,
        regiao: "Brazil",
        usarAceitadorMoedas: true,
        aceitadorMoedas: "nri",
        usarHopper: true,
        funii: "cubo",
        qualidadeMoedaHopper: "boa",
        usarControlador: true,
        controlador: "fotonota",
        usarAceitadorNotas: true,
        aceitadorNotas: "inovador",
        usarCashless: true,
        semDinheiro: "nayax",
        portoSemDinheiro: "COM1",
        serieSemDinheiro: "12345",
      },
      localizacao: {
        usarHorarioFuncionamento: true,
        horarioFuncionamento: [
          { dia: "Segunda-feira", inicio: "09:00", fim: "18:00", ativo: true },
          { dia: "Terça-feira", inicio: "09:00", fim: "18:00", ativo: true },
          { dia: "Quarta-feira", inicio: "09:00", fim: "18:00", ativo: true },
          { dia: "Quinta-feira", inicio: "09:00", fim: "18:00", ativo: true },
          { dia: "Sexta-feira", inicio: "09:00", fim: "18:00", ativo: true },
          { dia: "Sábado", inicio: "10:00", fim: "14:00", ativo: true },
          { dia: "Domingo", inicio: "10:00", fim: "14:00", ativo: true },
        ],
      },
    },
    registroSessao: [],
    colecoes: [],
    comandos: [
      {
        tipo: "reiniciarAplicativo",
        status: "pendente",
        criadoEm: "08:19 14 de novembro de 2024",
        usuario: "Alexandre Morozov",
      },
    ],
  },
  {
    id: "10201",
    nome: "10201 (Tacaruna)",
    status: [
      { type: "online", value: true },
      { type: "printer", value: true },
      { type: "paper", value: true },
      { type: "funnel", value: true },
      { type: "coinAcceptor", value: true },
      { type: "billValidator", value: true },
      { type: "cardReader", value: true },
      { type: "network", value: true },
    ],
    monitorMemoria: {
      value: "5 637,00 BRL",
      timeAgo: "2 anos atrás",
    },
    quantidade: "5637",
    papel: 68,
    funil: 86,
    departamento: "FotoNotaBR (Brasil)",
    predefinicaoLayout: "ATUALIZADOS",
    predefinicaoAnuncio: "falso",
    predefinicaoDocPhoto: "DOC BR",
    statusDispositivo: {
      aceitadorMoedas: {
        status: "conectado",
        name: "Aceitador de moedas",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      validadorBillet: {
        status: "conectado",
        name: "Validador de Billet",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      funil: {
        status: "conectado",
        name: "Funil",
        properties: [],
        optoEstados: 0,
        dispanceGlobalCounter: 0,
        valorMoeda: 0,
      },
      cortador: {
        status: "conectado",
        name: "Cortador",
        properties: [],
        tipoConexao: "",
        estaCortandoAgora: false,
      },
      controladorDispositivo: {
        status: "conectado",
        name: "Controlador de dispositivo",
        properties: [],
        ultimoPing: 0,
        revisaoSoftware: "",
      },
      impressoraDnp: {
        status: "conectado",
        name: "Impressora Dnp",
        properties: [],
        statusNativo: "",
        contagemMidia: 0,
      },
      monitorMemoria: {
        status: "conectado",
        name: "Monitor de memória",
        properties: [],
        memoriaDetalhes: [],
        rss: "",
        heapTotal: "",
        pilhaUsada: "",
        externo: "",
        buffersArray: "",
      },
      leitorCartaoBancario: {
        status: "conectado",
        name: "Leitor de cartão bancário",
        properties: [],
        tipoConexao: "",
      },
      navegador: {
        status: "conectado",
        name: "Navegador",
        properties: [],
        versao: "",
        versaoPrincipal: 0,
        protecaoDisco: "",
        chave: "",
      },
    },
    configuracoes: {
      nome: "Tacaruna",
      idQuiosque: "10201",
      departamento: "FotoNotaBR (Brasil)",
      fonteFoto: {
        instagram: true,
        doTelefone: true,
        facebook: true,
        fotoIdentificacao: true,
      },
      predefinicaoLayout: "ATUALIZADOS",
      predefinicaoAnuncio: "falso",
      predefinicaoDocPhoto: "DOC BR",
      pagamento: {},
      localidade: {},
      adicional: {},
      hardware: {},
      localizacao: {},
    },
    registroSessao: [],
    colecoes: [],
    comandos: [],
  },
  {
    id: "10200",
    nome: "10200 (Loja Recife)",
    status: [
      { type: "online", value: true },
      { type: "printer", value: false },
      { type: "paper", value: true },
      { type: "funnel", value: false },
      { type: "coinAcceptor", value: true },
      { type: "billValidator", value: true },
      { type: "cardReader", value: true },
      { type: "network", value: true },
    ],
    monitorMemoria: {
      value: "48 420,00 BRL",
      timeAgo: "7 meses atrás",
    },
    quantidade: "6666",
    papel: 63,
    funil: 49,
    departamento: "FotoNotaBR (Brasil)",
    predefinicaoLayout: "ATUALIZADOS",
    predefinicaoAnuncio: "falso",
    predefinicaoDocPhoto: "DOC BR",
    statusDispositivo: {
      aceitadorMoedas: {
        status: "conectado",
        name: "Aceitador de moedas",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      validadorBillet: {
        status: "conectado",
        name: "Validador de Billet",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      funil: {
        status: "conectado",
        name: "Funil",
        properties: [],
        optoEstados: 0,
        dispanceGlobalCounter: 0,
        valorMoeda: 0,
      },
      cortador: {
        status: "conectado",
        name: "Cortador",
        properties: [],
        tipoConexao: "",
        estaCortandoAgora: false,
      },
      controladorDispositivo: {
        status: "conectado",
        name: "Controlador de dispositivo",
        properties: [],
        ultimoPing: 0,
        revisaoSoftware: "",
      },
      impressoraDnp: {
        status: "conectado",
        name: "Impressora Dnp",
        properties: [],
        statusNativo: "",
        contagemMidia: 0,
      },
      monitorMemoria: {
        status: "conectado",
        name: "Monitor de memória",
        properties: [],
        memoriaDetalhes: [],
        rss: "",
        heapTotal: "",
        pilhaUsada: "",
        externo: "",
        buffersArray: "",
      },
      leitorCartaoBancario: {
        status: "conectado",
        name: "Leitor de cartão bancário",
        properties: [],
        tipoConexao: "",
      },
      navegador: {
        status: "conectado",
        name: "Navegador",
        properties: [],
        versao: "",
        versaoPrincipal: 0,
        protecaoDisco: "",
        chave: "",
      },
    },
    configuracoes: {
      nome: "Loja Recife",
      idQuiosque: "10200",
      departamento: "FotoNotaBR (Brasil)",
      fonteFoto: {
        instagram: true,
        doTelefone: true,
        facebook: true,
        fotoIdentificacao: true,
      },
      predefinicaoLayout: "ATUALIZADOS",
      predefinicaoAnuncio: "falso",
      predefinicaoDocPhoto: "DOC BR",
      pagamento: {},
      localidade: {},
      adicional: {},
      hardware: {},
      localizacao: {},
    },
    registroSessao: [],
    colecoes: [],
    comandos: [],
  },
  {
    id: "10199",
    nome: "10199 (Guararapes)",
    status: [
      { type: "online", value: true },
      { type: "printer", value: true },
      { type: "paper", value: true },
      { type: "funnel", value: true },
      { type: "coinAcceptor", value: true },
      { type: "billValidator", value: true },
      { type: "cardReader", value: true },
      { type: "network", value: true },
    ],
    monitorMemoria: {
      value: "2 731,00 BRL",
      timeAgo: "2 anos atrás",
    },
    quantidade: "2731",
    papel: 25,
    funil: 49,
    departamento: "FotoNotaBR (Brasil)",
    predefinicaoLayout: "ATUALIZADOS",
    predefinicaoAnuncio: "falso",
    predefinicaoDocPhoto: "DOC BR",
    statusDispositivo: {
      aceitadorMoedas: {
        status: "conectado",
        name: "Aceitador de moedas",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      validadorBillet: {
        status: "conectado",
        name: "Validador de Billet",
        properties: [],
        moeda: "BRL",
        moedaInibirStr: "",
        debugPollCount: 0,
        codigosCaminho: [],
      },
      funil: {
        status: "conectado",
        name: "Funil",
        properties: [],
        optoEstados: 0,
        dispanceGlobalCounter: 0,
        valorMoeda: 0,
      },
      cortador: {
        status: "conectado",
        name: "Cortador",
        properties: [],
        tipoConexao: "",
        estaCortandoAgora: false,
      },
      controladorDispositivo: {
        status: "conectado",
        name: "Controlador de dispositivo",
        properties: [],
        ultimoPing: 0,
        revisaoSoftware: "",
      },
      impressoraDnp: {
        status: "conectado",
        name: "Impressora Dnp",
        properties: [],
        statusNativo: "",
        contagemMidia: 0,
      },
      monitorMemoria: {
        status: "conectado",
        name: "Monitor de memória",
        properties: [],
        memoriaDetalhes: [],
        rss: "",
        heapTotal: "",
        pilhaUsada: "",
        externo: "",
        buffersArray: "",
      },
      leitorCartaoBancario: {
        status: "conectado",
        name: "Leitor de cartão bancário",
        properties: [],
        tipoConexao: "",
      },
      navegador: {
        status: "conectado",
        name: "Navegador",
        properties: [],
        versao: "",
        versaoPrincipal: 0,
        protecaoDisco: "",
        chave: "",
      },
    },
    configuracoes: {
      nome: "Guararapes",
      idQuiosque: "10199",
      departamento: "FotoNotaBR (Brasil)",
      fonteFoto: {
        instagram: true,
        doTelefone: true,
        facebook: true,
        fotoIdentificacao: true,
      },
      predefinicaoLayout: "ATUALIZADOS",
      predefinicaoAnuncio: "falso",
      predefinicaoDocPhoto: "DOC BR",
      pagamento: {},
      localidade: {},
      adicional: {},
      hardware: {},
      localizacao: {},
    },
    registroSessao: [],
    colecoes: [],
    comandos: [],
  },
]

export const quiosquesService = {
  async getQuiosques(): Promise<Quiosque[]> {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockQuiosques
  },

  async getQuiosqueById(id: string): Promise<Quiosque | null> {
    await new Promise((resolve) => setTimeout(resolve, 300))
    return mockQuiosques.find((q) => q.id === id) || null
  },
}
