import { MolduraCompleta } from "../types/moluras"


// Função que simula chamada à API (futuro real)
export const getMolduras = async (): Promise<MolduraCompleta[]> => {
  // Simula delay de API
  await new Promise((resolve) => setTimeout(resolve, 500))
  return moldurasCompletasData
}
// Mock local usado enquanto não há backend
const moldurasCompletasData: MolduraCompleta[] = [
  {
    id: 1,
    descricao: "Natal",
    grupoId: 1,
    grupoNome: "Aniversário",
    backgroundColor: "#dc2626",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 4,
    posicaoY: 19,
    tamanhoImagem: 60,
    rotacaoImagem: 0,
    ativa: true,
    dataCriacao: "2024-01-15",
    dataAtualizacao: "2024-01-15",
  },
  {
    id: 2,
    descricao: "Teste 2",
    grupoId: 1,
    grupoNome: "Aniversário",
    backgroundColor: "#7c3aed",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 5,
    posicaoY: 5,
    tamanhoImagem: 45,
    rotacaoImagem: 15,
    ativa: true,
    dataCriacao: "2024-01-16",
    dataAtualizacao: "2024-01-16",
  },
  {
    id: 3,
    descricao: "Teste 2",
    grupoId: 1,
    grupoNome: "Aniversário",
    backgroundColor: "#10b981",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 35,
    posicaoY: 35,
    tamanhoImagem: 70,
    rotacaoImagem: -10,
    ativa: true,
    dataCriacao: "2024-01-17",
    dataAtualizacao: "2024-01-17",
  },
  {
    id: 4,
    descricao: "Teste",
    grupoId: 1,
    grupoNome: "Aniversário",
    backgroundColor: "#10b981",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 5,
    posicaoY: 5,
    tamanhoImagem: 55,
    rotacaoImagem: 0,
    ativa: true,
    dataCriacao: "2024-01-18",
    dataAtualizacao: "2024-01-18",
  },
  {
    id: 5,
    descricao: "Casamento Elegante",
    grupoId: 2,
    grupoNome: "Casamento",
    backgroundColor: "#f8fafc",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 10,
    posicaoY: 10,
    tamanhoImagem: 65,
    rotacaoImagem: 5,
    ativa: true,
    dataCriacao: "2024-02-01",
    dataAtualizacao: "2024-02-01",
  },
  {
    id: 6,
    descricao: "Formatura Dourada",
    grupoId: 3,
    grupoNome: "Formatura",
    backgroundColor: "#fbbf24",
    foregroundImage: "/placeholder.svg?height=50&width=50",
    posicaoX: 15,
    posicaoY: 25,
    tamanhoImagem: 50,
    rotacaoImagem: 0,
    ativa: false,
    dataCriacao: "2024-02-15",
    dataAtualizacao: "2024-02-15",
  },
]
